permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Yiner
  email: lijiuyang1992@gmail.com
  link: http://pyiner.com
  github: https://github.com/Yiner/

# 站点信息
title: Yiner的博客
description: Yiner的博客
url: http://pyiner.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/upload/gavatar/gavatar.png
favicon: /public/upload/gavatar/favicon.ico

# disqus 设置
disqus:
  shortname: suyan-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
